service_name: travis-ci
repo_token: iJDBxflj9nJWTjojsIKj2N2bZ5qii0uQR


# for php-coveralls
src_dir: ./api/app
coverage_clover: ./api/reports/coverage/clover.xml
json_path: ./api/reports/coverage/coveralls-upload.json