language: php
php:
  - 5.5

before_script:
  - npm install --quiet -g gulp bower newman
  - npm install
  - bower install
  - gulp
  - composer install --working-dir api
  - php -S localhost:8000 -t ./api/public &
  - sleep 5 #give server some time to boot

script:
  - npm test

after_script:
  - gulp coveralls