language: php
php:
  - 5.5

addons:
  postgresql: "9.3"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libnotify-bin

before_script:

  - psql -c 'create database nglume;' -U postgres
  - npm install --quiet -g gulp newman
  - npm install
  - gulp bower:install
  - gulp build
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --working-dir api
  - travis_retry composer install --prefer-source --no-interaction
  - cp ./api/.travis.env ./api/.env
  - php composer dumpautoload -o
  - php ./api/artisan migrate --seed --env=travis
  - php ./api/artisan serve --port 8080 --env=travis &
  - gem install mailcatcher
  - mailcatcher
  - sleep 5 #give server some time to boot

script:
  - gulp test

after_script:
  - php ./vendor/bin/coveralls
