sudo:false
language: php
php:
 - 5.5

addons:
  postgresql: "9.3"
  apt:
    sources:
    - libnotify-bin
    - beanstalkd

services:
  - redis-server

install:
  # Install phantomjs@2.0.0 (remove this when https://github.com/travis-ci/travis-ci/issues/3225 is resolved)
  - mkdir travis-phantomjs
  - travis_retry wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  - tar -xvf $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -C $PWD/travis-phantomjs
  - export PATH=$PWD/travis-phantomjs:$PATH

  - cp ./api/.travis.env ./api/.env

  - travis_retry npm install --no-spin --quiet -g gulp http-server
  - travis_retry npm install --no-spin
  - travis_retry gulp bower:install
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --working-dir api
  - travis_retry composer install --prefer-source --no-interaction
  - travis_retry gem install mailcatcher

before_script:

  - psql -c 'create database spira;' -U postgres
  - gulp build
  - php ./api/artisan migrate --seed
  - php ./api/artisan serve --port 8000 --host 127.0.0.1 --quiet 2>&1 >/dev/null & # start api server
  - http-server ./app/build/ -p 8001 2>&1 >/dev/null & # start webserver
  - mailcatcher # start mailcatcher server
  - beanstalkd -d -l 127.0.0.1 -p 11300 # start queue listener
  - sleep 5 # give server some time to boot

script:
  - gulp test
  - ./node_modules/.bin/cucumber.js

after_script:
  - php ./vendor/bin/coveralls -v
