language: php
php:
  - hhvm

addons:
  postgresql: "9.3"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libnotify-bin
  # hhvm postgres plugin build
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:boost-latest/ppa -y
  - sudo apt-get update
  - sudo apt-get install gcc-4.8 g++-4.8 hhvm-dev libboost1.55-all-dev libpq-dev
  # configure gcc & g++
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.6 40 --slave /usr/bin/g++ g++ /usr/bin/g++-4.6
  - sudo update-alternatives --set gcc /usr/bin/gcc-4.8
  # install glog
  - cd /tmp
  - wget https://google-glog.googlecode.com/files/glog-0.3.3.tar.gz
  - tar zxvf glog-0.3.3.tar.gz
  - cd glog-0.3.3
  - ./configure
  - sudo make && sudo make install
  # install jemalloc
  - cd /tmp
  - wget http://www.canonware.com/download/jemalloc/jemalloc-3.6.0.tar.bz2
  - tar xjvf jemalloc-3.6.0.tar.bz2
  - cd jemalloc-3.6.0
  - sudo ./configure #--prefix=$CMAKE_PREFIX_PATH
  - sudo make && sudo make install
  # get hhvm-ext-install shell file
  - wget https://raw.githubusercontent.com/estebanmatias92/docker-hhvm/master/hhvm-ext-install
  - sudo chmod 777 hhvm-ext-install
  - PHP_INI_DIR=/etc/hhvm/
  # install hhvm-pgsql
  - cd /tmp
  - git clone https://github.com/PocketRent/hhvm-pgsql.git ./hhvm-pgsql && cd ./hhvm-pgsql && git checkout tags/3.7.0
  - sudo hphpize
  - sudo cmake .
  - sudo make
  - sudo mv pgsql.so /etc/hhvm/pgsql.so
  - sudo -- sh -c "printf 'extension_dir = /etc/hhvm\nhhvm.extensions[pgsql] = pgsql.so' >> /etc/hhvm/php.ini"
#  - sudo ./hhvm-ext-install PocketRent/hhvm-pgsql

before_script:

  - psql -c 'create database spira;' -U postgres
  - npm install --quiet -g gulp newman http-server
  - npm install
  - gulp bower:install
  - gulp build
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --working-dir api
  - travis_retry composer install --prefer-source --no-interaction
  - composer dumpautoload -o --working-dir api
  - cp ./api/.travis.env ./api/.env
  - php ./api/artisan migrate --seed
  - php ./api/artisan serve --port 8000 --host 127.0.0.1 --quiet 2>&1 >/dev/null & #start api server
  - http-server ./app/build/ -p 8001 2>&1 >/dev/null & #start webserver
  - gem install mailcatcher
  - mailcatcher # start mailcatcher server
  - sleep 5 #give server some time to boot

script:
  - gulp test
  - ./node_modules/.bin/cucumber.js

after_script:
  - php ./vendor/bin/coveralls -v
