language: php
php:
  - 5.5

before_script:
  - npm install --quiet -g gulp bower
  - npm install
  - bower install
  - gulp
  - composer install --working-dir api

script: npm test

after_script:
  - gulp coveralls