language: php
php:
 - 5.6

addons:
  postgresql: "9.3"

services:
  - elasticsearch


before_install:
  - sudo apt-get update -qq

install:
  - rm ./env/.env && cp ./env/.travis.env ./env/.env #replace the .env file with a custom travis one

  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction

before_script:
  # rest of the stuff
  - psql -c 'create database spira;' -U postgres
  - php artisan migrate
  - php artisan serve --port 8008 --host 127.0.0.1 --quiet 2>&1 >/dev/null &

script:
  - php ./vendor/bin/phpunit --colors --configuration ./phpunit.xml --coverage-clover=./reports/coverage/clover.xml

after_script:
  - php ./vendor/bin/coveralls -v
