language: php
php:
  - 5.5

before_script:
  - npm install --quiet -g gulp bower newman
  - npm install
  - bower install
  - gulp
  - composer install --working-dir api
  - ./api/artisan serve --port 9000 &
  - sleep 5 #give artisan serve some time to boot

script:
  - npm test
  - newman -c ./api/postman/larvae.json.postman_collection -e ./api/postman/larvae-travisci.postman_environment

after_script:
  - gulp coveralls