language: php
php:
  - hhvm

addons:
  postgresql: "9.3"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libnotify-bin
  # hhvm postgres plugin build
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install gcc-4.8 g++-4.8 hhvm-dev
  # hhvm fix for hhvm 3.5.0
  - curl 'https://raw.githubusercontent.com/facebook/hhvm/573d6fc0d2745e96ee9775f31dc993919086fc7a/hphp/runtime/version.h' > /tmp/version.h
  - sudo cp /tmp/version.h /usr/include/hphp/runtime/version.h

  - cd /tmp
  - wget "https://github.com/PocketRent/hhvm-pgsql/raw/releases/3.6.0/ubuntu/precise/pgsql.so"
  - sudo mv pgsql.so /etc/hhvm/pgsql.so
  - sudo -- sh -c "printf 'extension_dir = /etc/hhvm\nhhvm.extensions[pgsql] = pgsql.so' >> /etc/hhvm/php.ini"
  - sudo service hhvm restart
  - cd $TRAVIS_BUILD_DIR


before_script:

  - psql -c 'create database spira;' -U postgres
  - npm install --quiet -g gulp newman http-server
  - npm install
  - gulp bower:install
  - gulp build
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --working-dir api
  - travis_retry composer install --prefer-source --no-interaction
  - composer dumpautoload -o --working-dir api
  - cp ./api/.travis.env ./api/.env
  - hhvm ./api/artisan migrate --seed
  - hhvm ./api/artisan serve --port 8000 --host 127.0.0.1 --quiet 2>&1 >/dev/null & #start api server
  - http-server ./app/build/ -p 8001 2>&1 >/dev/null & #start webserver
  - gem install mailcatcher
  - mailcatcher # start mailcatcher server
  - sleep 5 #give server some time to boot

script:
  - gulp test
  - ./node_modules/.bin/cucumber.js

after_script:
  - hhvm ./vendor/bin/coveralls -v
