language: php
php:
  - 5.5

before_script:
  - npm install --quiet -g gulp bower newman
  - npm install
  - bower install
  - gulp
  - composer install --working-dir api
  - php -S localhost:8000 -t ./api/public &
  - sleep 5 #give server some time to boot

script:
  - npm test
  - sudo newman -c ./api/postman/larvae.json.postman_collection -e ./api/postman/larvae-travisci.postman_environment

after_script:
  - gulp coveralls