language: php
php:
  - hhvm

addons:
  postgresql: "9.3"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libnotify-bin hhvm-dev gcc-4.8 g++-4.8
  - wget https://raw.githubusercontent.com/estebanmatias92/docker-hhvm/master/hhvm-ext-install
  - sudo chmod 777 hhvm-ext-install
  - PHP_INI_DIR=/etc/hhvm/
  - sudo ./hhvm-ext-install dstelter/hhvm-pgsql

before_script:

  - psql -c 'create database spira;' -U postgres
  - npm install --quiet -g gulp newman http-server
  - npm install
  - gulp bower:install
  - gulp build
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --working-dir api
  - travis_retry composer install --prefer-source --no-interaction
  - composer dumpautoload -o --working-dir api
  - cp ./api/.travis.env ./api/.env
  - php ./api/artisan migrate --seed
  - php ./api/artisan serve --port 8000 --host 127.0.0.1 --quiet 2>&1 >/dev/null & #start api server
  - http-server ./app/build/ -p 8001 2>&1 >/dev/null & #start webserver
  - gem install mailcatcher
  - mailcatcher # start mailcatcher server
  - sleep 5 #give server some time to boot

script:
  - gulp test
  - ./node_modules/.bin/cucumber.js

after_script:
  - php ./vendor/bin/coveralls -v
