language: php
php:
 - 7.0

addons:
  postgresql: "9.3"

services:
  - redis-server
  - mysql
  - elasticsearch

env:
  global:
    - FORUM_DB_DATABASE=vanilla
    - FORUM_DB_HOST=127.0.0.1
    - FORUM_DB_USERNAME=travis
    - FORUM_DB_PASSWORD=
    - VANILLA_JSCONNECT_CLIENT_ID=a-client-id-random-string
    - VANILLA_JSCONNECT_SECRET=a-secret-phrase-random-string
    - VANILLA_SERVER_HOST=127.0.0.1
    - VANILLA_SERVER_PORT=8008
    - VANILLA_ADMIN_NAME=admin
    - VANILLA_ADMIN_EMAIL=admin@admin.com
    - VANILLA_ADMIN_PASSWORD=password

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libnotify-bin beanstalkd
  - nvm install 5.4.0 && nvm use 5.4.0 && npm install -g npm
  - mysql -e 'create database vanilla;'

install:
  # Install phantomjs@2.0.0 (remove this when https://github.com/travis-ci/travis-ci/issues/3225 is resolved)
  - mkdir travis-phantomjs
  - travis_retry wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  - tar -xvf $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -C $PWD/travis-phantomjs
  - export PATH=$PWD/travis-phantomjs:$PATH

  - rm ./api/.env && cp ./api/.travis.env ./api/.env #replace the .env file with a custom travis one

  - travis_retry npm install --no-spin --quiet -g gulp http-server
  - travis_retry npm install --no-spin
  - travis_retry gulp bower:install
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --working-dir forum
  - travis_retry composer install --prefer-source --no-interaction --working-dir api
  - travis_retry composer install --prefer-source --no-interaction
  - travis_retry gem install mailcatcher

before_script:
  # Additional PHP config
  - phpenv config-add travis.php.ini
  # rest of the stuff
  - php -S 127.0.0.1:8008 ./forum/server.php >& /dev/null & # start forum server
  - psql -c 'create database spira;' -U postgres
  - gulp build
  - php ./api/artisan migrate --seed
  - php ./api/artisan serve --port 8000 --host 127.0.0.1 --quiet 2>&1 >/dev/null & # start api server
  - http-server ./app/build/ -p 8001 2>&1 >/dev/null & # start webserver
  - mailcatcher # start mailcatcher server
  - beanstalkd -d -l 127.0.0.1 -p 11300 # start queue listener
  - sleep 5 # give server some time to boot

script:
  - gulp test:app
  - ./api/vendor/bin/phpunit --colors --configuration ./api/phpunit.xml --coverage-clover=./reports/coverage/api/clover.xml
  - ./node_modules/.bin/cucumber.js --tags ~@ignore #skip @ignored features

after_script:
  - php ./vendor/bin/coveralls -v
