
data:
  extends:
    file: ./docker/common-services.yml
    service: datavolume

logviewer:
  extends:
    file: ./docker/common-services.yml
    service: logviewer
  volumes_from:
    - data

database:
  extends:
    file: ./docker/common-services.yml
    service: database
  ports:
    - "5432:5432"

vanilladatabase:
  extends:
    file: ./docker/common-services.yml
    service: vanilladatabase
  ports:
    - "3306:3306"

cache:
  extends:
    file: ./docker/common-services.yml
    service: cache

queue:
  extends:
    file: ./docker/common-services.yml
    service: queue

queuerunner:
  extends:
    file: ./docker/common-services.yml
    service: queuerunner
  links:
    - mailcatcher:mailcatcher
    - queue:queue
    - cache:cache
    - database:database
    - web:web
  volumes_from:
    - data

mailcatcher:
  extends:
    file: ./docker/common-services.yml
    service: mailcatcher

php:
  extends:
    file: ./docker/common-services.yml
    service: php
  links:
    - database:database
    - vanilladatabase:vanilladatabase
    - cache:cache
    - queue:queue
    - mailcatcher:mailcatcher
  volumes_from:
    - data

web:
  extends:
    file: ./docker/common-services.yml
    service: web
  ports:
    - "80:80"
    - "8080:8080"
  links:
    - php:php
    - logviewer:logviewer
    - mailcatcher:mailcatcher
    - apimock:apimock
  volumes_from:
    - data

devtools:
  extends:
    file: ./docker/common-services.yml
    service: devtools
  links:
    - web:web
    - mailcatcher:mailcatcher
    - database:database
    - vanilladatabase:vanilladatabase
    - cache:cache
    - queue:queue
  volumes_from:
    - data

apimock:
  extends:
    file: ./docker/common-services.yml
    service: apimock
  volumes_from:
    - data