
data:  
  image: spira/docker-data
  volumes:
    - /data:/data
  privileged: true

db:
  image: postgres
  environment:
    - POSTGRES_PASSWORD=spira
    - POSTGRES_USER=spira
  ports:
    - "5432:5432"

redis:
  image: redis

queue:
  image: spira/docker-beanstalkd

queuerunner:
  image: spira/docker-artisan-queue-runner
  links:
    - lumen
  volumes_from:
    - data

mailcatcher:
  image: schickling/mailcatcher
  ports:
    - "1080:1080"

php:  
#  image: spira/docker-hhvm # @todo switch to hhvm when Predis works with hhvm
  image: spira/docker-phpfpm
  volumes_from:
    - data
  links:
    - db:db
    - redis:redis
    - queue:queue
    - mailcatcher:mailcatcher
  environment:
    - API_PATH=/api
    - XDEBUG_ENABLED=true
  privileged: true

web:  
  image: spira/docker-nginx
  volumes_from:
    - data
  links:
    - php:php
  ports:
    - "80:80"
    - "8080:8080"
  environment:
      - NGINX_VHOSTS=vhosts/nginx/*.local.conf
  privileged: true


npm:
  image: spira/docker-npm
  volumes_from:
    - data
  privileged: true

gulp:
  image: spira/docker-gulp
  volumes_from:
    - data
  links:
    - web:nginx
    - mailcatcher:mailcatcher
  privileged: true

phpcomposer:
  image: spira/docker-composer
  volumes_from:
    - data
  privileged: true

artisan:
  image: spira/docker-artisan
  volumes_from:
    - data
  links:
    - db:db
    - redis:redis
    - queue:queue
  privileged: true

ssh:
  image: spira/docker-ssh
  volumes_from:
      - data
  privileged: false
  ports:
      - "42222:22"
  links:
      - db:db
      - redis:redis
      - queue:queue
  environment:
      - SSH_PASSWORD=spira

lumen:
  image: spira/docker-lumen
  volumes_from:
    - data
  links:
    - mailcatcher:mailcatcher
    - queue:queue
    - redis:redis
    - db:db
  environment:
    - API_PATH=/api
    - API_DOTENV=.local.env