
data:
  image: spira/docker-data
  volumes:
    - /data:/data
  privileged: true

db:
  image: postgres
  environment:
    - POSTGRES_PASSWORD=spira
    - POSTGRES_USER=spira
  ports:
    - "5432:5432"

redis:
  image: redis

queue:
  image: spira/docker-beanstalkd

queuerunner:
  image: spira/docker-artisan-queue-runner
  links:
    - lumen
  volumes_from:
    - data

mailcatcher:
  image: schickling/mailcatcher
  ports:
    - "1080:1080"

php:  
  image: spira/docker-hhvm
#  image: spira/docker-phpfpm
  volumes_from:
    - data
  links:
    - db:db
    - redis:redis
    - queue:queue
    - mailcatcher:mailcatcher
  environment:
    - API_PATH=/api
    - XDEBUG_ENABLED=true
  privileged: true

web:  
  image: spira/docker-nginx
  volumes_from:
    - data
  links:
    - php:php
  ports:
    - "80:80"
    - "8080:8080"
  environment:
      - NGINX_VHOSTS=vhosts/nginx/*.local.conf
  privileged: true

devtools:
  image: spira/docker-dev-tools:latest
#  image: spira/docker-dev-tools:phantomjs-1.9.8
  volumes_from:
    - data
  privileged: true
  links:
    - web:nginx
    - mailcatcher:mailcatcher
    - db:db
    - redis:redis
    - queue:queue

lumen:
  image: spira/docker-lumen
  working_dir: /data
  volumes_from:
    - data
  links:
    - mailcatcher:mailcatcher
    - queue:queue
    - redis:redis
    - db:db
    - web:web
  environment:
    - API_PATH=/api
    - API_DOTENV=.local.env
