
data:
  image: spira/docker-data
  volumes:
    - /data:/data
  privileged: true

logviewer:
  image: spira/docker-clarity
  volumes_from:
    - data

database:
  image: postgres:9.4
  env_file:
    - .common.env
    - .local.env
  ports:
    - "5432:5432"

cache:
  image: redis

queue:
  image: spira/docker-beanstalkd

queuerunner:
  image: spira/docker-artisan-queue-runner
  links:
    - mailcatcher:mailcatcher
    - queue:queue
    - cache:cache
    - database:database
    - web:web
  volumes_from:
    - data
  env_file:
    - .common.env
    - .local.env

mailcatcher:
  image: schickling/mailcatcher

php:
  image: spira/docker-hhvm
#  image: spira/docker-phpfpm
  volumes_from:
    - data
  links:
    - database:database
    - cache:cache
    - queue:queue
    - mailcatcher:mailcatcher
  env_file:
      - .common.env
      - .local.env
      - .secret.env
  privileged: true

web:
  image: spira/docker-nginx
  volumes_from:
    - data
  links:
    - php:php
    - logviewer:logviewer
    - mailcatcher:mailcatcher
    - apimock:apimock
  ports:
    - "80:80"
    - "8080:8080"
  env_file:
    - .common.env
    - .local.env
  privileged: true

devtools:
  image: spira/docker-dev-tools:latest
  working_dir: /data
#  image: spira/docker-dev-tools:phantomjs-1.9.8
  volumes_from:
    - data
  privileged: true
  env_file:
    - .common.env
    - .local.env
    - .secret.env
  links:
    - web:web
    - mailcatcher:mailcatcher
    - database:database
    - cache:cache
    - queue:queue

apimock:
  image: spira/docker-drakov
  volumes_from:
    - data
  env_file:
    - .common.env
    - .local.env