# QA configuration - this is similar to the dev container except it uses the spira/spira container that was created
# by the build script.

spira:
  image: spira/spira:%spira_container_tag%
  volumes:
    - /data #note we are not mounting to host. otherwise it would be /qa/data

logviewer:
  extends:
    file: ./docker/common-services.yml
    service: logviewer
  volumes_from:
    - spira
  env_file:
    - ./docker/.qa.env

database:
  extends:
    file: ./docker/common-services.yml
    service: database
  env_file:
    - ./docker/.qa.env

vanilladatabase:
  extends:
    file: ./docker/common-services.yml
    service: vanilladatabase
  env_file:
    - ./docker/.qa.env

cache:
  extends:
    file: ./docker/common-services.yml
    service: cache
  env_file:
    - ./docker/.qa.env

elasticsearch:
  extends:
    file: ./docker/common-services.yml
    service: elasticsearch
  env_file:
    - ./docker/.qa.env

queue:
  extends:
    file: ./docker/common-services.yml
    service: queue
  env_file:
    - ./docker/.qa.env

queuerunner:
  extends:
    file: ./docker/common-services.yml
    service: queuerunner
  links:
    - mailcatcher:mailcatcher
    - queue:queue
    - cache:cache
    - database:database
    - web:web
  volumes_from:
    - spira
  env_file:
    - ./docker/.qa.env

mailcatcher:
  extends:
    file: ./docker/common-services.yml
    service: mailcatcher
  env_file:
    - ./docker/.qa.env

php:
  extends:
    file: ./docker/common-services.yml
    service: php
  links:
    - database:database
    - vanilladatabase:vanilladatabase
    - cache:cache
    - queue:queue
    - mailcatcher:mailcatcher
    - elasticsearch:elasticsearch
  volumes_from:
    - spira
  env_file:
    - ./docker/.qa.env

web:
  extends:
    file: ./docker/common-services.yml
    service: web
  ports:
    - "%expose_port%:80" # for QA we only expose port 80 as the web container (nginx) handles port mapping itself with proxies
  links:
    - php:php
    - logviewer:logviewer
    - mailcatcher:mailcatcher
    - apimock:apimock
  volumes_from:
    - spira
  env_file:
    - ./docker/.qa.env

devtools:
  extends:
    file: ./docker/common-services.yml
    service: devtools
  links:
    - web:web
    - mailcatcher:mailcatcher
    - database:database
    - vanilladatabase:vanilladatabase
    - cache:cache
    - queue:queue
    - elasticsearch:elasticsearch
  volumes_from:
    - spira
  env_file:
    - ./docker/.qa.env

apimock:
  extends:
    file: ./docker/common-services.yml
    service: apimock
  volumes_from:
    - spira
  env_file:
    - ./docker/.qa.env