
lbhaproxy:
  extends:
    file: ./docker/common-services.yml
    service: lbhaproxy
  links:
    - api
    - mailcatcher
  env_file:
    - ./docker/.local.env

#data:
#  extends:
#    file: ./docker/common-services.yml
#    service: datavolume
#  env_file:
#    - ./docker/.local.env

#logviewer:
#  extends:
#    file: ./docker/common-services.yml
#    service: logviewer
#  volumes_from:
#    - data
#  env_file:
#    - ./docker/.local.env

database:
  extends:
    file: ./docker/common-services.yml
    service: database
  ports:
    - "5432:5432"
  env_file:
    - ./docker/.local.env

vanilladatabase:
  extends:
    file: ./docker/common-services.yml
    service: vanilladatabase
  ports:
    - "3306:3306"
  env_file:
    - ./docker/.local.env

cache:
  extends:
    file: ./docker/common-services.yml
    service: cache
  ports:
    - "6379:6379"
  env_file:
    - ./docker/.local.env

elasticsearch:
  extends:
    file: ./docker/common-services.yml
    service: elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"
  env_file:
    - ./docker/.local.env

queue:
  extends:
    file: ./docker/common-services.yml
    service: queue
  env_file:
    - ./docker/.local.env

api:
  extends:
    file: ./docker/common-services.yml
    service: api
  links:
    - mailcatcher
    - queue
    - cache
    - database
  environment:
    - VIRTUAL_HOST=local.api.spira.io
    - NGINX_VHOSTS=/data/docker/config/vhosts/dev/*.conf

queuerunner:
  extends:
    file: ./docker/common-services.yml
    service: queuerunner
  links:
    - mailcatcher
    - queue
    - cache
    - database
  volumes_from:
    - api
  env_file:
    - ./docker/.local.env

mailcatcher:
  extends:
    file: ./docker/common-services.yml
    service: mailcatcher
  env_file:
    - ./docker/.local.env
  environment:
    - VIRTUAL_HOST=local.mailcatcher.spira.io
    - EXCLUDE_PORTS=1025

devtools:
  extends:
    file: ./docker/common-services.yml
    service: devtools
  links:
    - mailcatcher:mailcatcher
    - database:database
    - vanilladatabase:vanilladatabase
    - cache:cache
    - queue:queue
    - elasticsearch:elasticsearch
  volumes_from:
    - api
  volumes:
    - /cache:/cache
  env_file:
    - ./docker/.local.env

