
data:
  image: spira/docker-data
  volumes:
    - /data:/data
  environment:
    - DATA_ROOT=/data #default DATA_ROOT environment value for the other containers to inherit from
  privileged: true
  
logviewer:
  image: spira/docker-clarity
  volumes_from:
    - data

database:
  image: postgres:9.4
  environment:
    - POSTGRES_PASSWORD=spira
    - POSTGRES_USER=spira
  ports:
    - "5432:5432"

cache:
  image: redis

queue:
  image: spira/docker-beanstalkd

queuerunner:
  image: spira/docker-artisan-queue-runner
  links:
    - mailcatcher:mailcatcher
    - queue:queue
    - cache:cache
    - database:database
    - web:web
  volumes_from:
    - data

mailcatcher:
  image: schickling/mailcatcher

php:  
  image: spira/docker-hhvm
#  image: spira/docker-phpfpm
  volumes_from:
    - data
  links:
    - database:database
    - cache:cache
    - queue:queue
    - mailcatcher:mailcatcher
  environment:
    - API_PATH=/api
    - XDEBUG_ENABLED=true
  privileged: true

web:  
  image: spira/docker-nginx
  volumes_from:
    - data
  links:
    - php:php
    - logviewer:logviewer
    - mailcatcher:mailcatcher
  ports:
    - "80:80"
    - "8080:8080"
  environment:
    - DATA_ROOT=/data
    - API_PATH=/api
    - NGINX_VHOSTS=vhosts/nginx/*.local.conf
  privileged: true

devtools:
  image: spira/docker-dev-tools:latest
  working_dir: /data
#  image: spira/docker-dev-tools:phantomjs-1.9.8
  volumes_from:
    - data
  privileged: true
  links:
    - web:nginx
    - mailcatcher:mailcatcher
    - database:database
    - cache:cache
    - queue:queue
