
spira:
  image: spira/spira
  volumes:
    - /data #note we are not mounting to host. otherwise it would be /qa/data

logviewer:
  image: spira/docker-clarity
  volumes_from:
    - spira

database:
  image: postgres:9.4
  env_file:
    - .common.env
    - .qa.env
  ports:
    - "5432:5432"

cache:
  image: redis

queue:
  image: spira/docker-beanstalkd

queuerunner:
  image: spira/docker-artisan-queue-runner
  links:
    - mailcatcher:mailcatcher
    - queue:queue
    - cache:cache
    - database:database
    - web:web
  volumes_from:
    - spira

mailcatcher:
  image: schickling/mailcatcher

php:  
  image: spira/docker-hhvm
  volumes_from:
    - spira
  links:
    - database:database
    - cache:cache
    - queue:queue
    - mailcatcher:mailcatcher
  env_file:
    - .common.env
    - .qa.env
  privileged: true

web:  
  image: spira/docker-nginx
  volumes_from:
    - spira
  links:
    - php:php
    - logviewer:logviewer
    - mailcatcher:mailcatcher
  ports:
    - "80:80"
    - "8080:8080"
  env_file:
    - .common.env
    - .qa.env
  privileged: true

# keep devtools as it is needed for image building
devtools:
  image: spira/docker-dev-tools:latest
  working_dir: /data
  volumes_from:
    - spira
  privileged: true
  links:
    - web:web
    - mailcatcher:mailcatcher
    - database:database
    - cache:cache
    - queue:queue
  env_file:
    - .common.env
    - .qa.env
