
data:  
  image: nglume/docker-data
  volumes:
    - /data:/data
  environment:
    - API_PATH=/api
    - API_DOTENV=.local.env
  privileged: true
  links:
   - mailcatcher:mailcatcher
   - queue:queue

db:
  image: postgres
  environment:
    - POSTGRES_PASSWORD=nglume
    - POSTGRES_USER=nglume
  ports:
    - "5432:5432"

redis:
  image: redis

queue:
  image: nglume/docker-beanstalkd

queuerunner:
  image: nglume/docker-artisan-queue-runner
  volumes_from:
    - data

mailcatcher:
  image: schickling/mailcatcher
  ports:
    - "1080:1080"

php:  
  image: nglume/docker-phpfpm
  volumes_from:
    - data
  links:
    - db:db
    - redis:redis
    - queue:queue
    - mailcatcher:mailcatcher
  environment:
    - API_PATH=/api
    - XDEBUG_ENABLED=true
  privileged: true

web:  
  image: nglume/docker-nginx
  volumes_from:
    - data
  links:
    - php:fpm
  ports:
    - "80:80"
    - "8080:8080"
  environment:
      - NGINX_VHOSTS=vhosts/nginx/*.local.conf
  privileged: true


npm:
  image: nglume/docker-npm
  volumes_from:
    - data
  privileged: true

gulp:
  image: nglume/docker-gulp
  volumes_from:
    - data
  links:
    - web:nginx
    - mailcatcher:mailcatcher
  privileged: true

phpcomposer:
  image: nglume/docker-composer
  volumes_from:
    - data
  privileged: true

artisan:
  image: nglume/docker-artisan
  volumes_from:
    - data
  links:
    - db:db
    - redis:redis
    - queue:queue
  privileged: true

ssh:
  image: nglume/docker-ssh
  volumes_from:
      - data
  privileged: false
  ports:
      - "42222:22"
  links:
      - db:db
      - redis:redis
      - queue:queue
  environment:
      - SSH_PASSWORD=nglume