# This common-services.yml definition holds all the image definitions and environment linking for the images.
# It is intended to use the docker-compose extends functionality to use these definitions to build a docker-compose file

lbnginx:
  image: spira/docker-nginx
  env_file:
    - .common.env
    - .secret.env
  volumes:
    - ../docker/lbnginx:/data
  ports:
    - '80:80'

database:
  image: postgres:9.4
  env_file:
    - .common.env

vanilladatabase:
  image: mariadb:10.0
  env_file:
    - .common.env

cache:
  image: redis

queue:
  image: spira/docker-beanstalkd

queuerunner:
  image: spira/docker-artisan-queue-runner
  env_file:
    - .common.env

mailcatcher:
  image: schickling/mailcatcher

api:
  image: spira/docker-nginx-php
  env_file:
    - .common.env
    - .secret.env
  volumes:
    - ../api:/data
  expose:
    - "8080"
  privileged: true

app:
  image: spira/docker-nginx
  env_file:
    - .common.env
    - .secret.env
  volumes:
    - ../app:/data
  expose:
    - "8081"
  privileged: true

forum:
  image: spira/docker-nginx-php
  env_file:
    - .common.env
    - .secret.env
  volumes:
    - ../forum:/data
  expose:
    - "80"
  privileged: true

devtools:
  image: spira/docker-dev-tools
  working_dir: /data
  privileged: true
  volumes:
    - ../:/data
  env_file:
    - .common.env
    - .secret.env

elasticsearch:
  image: elasticsearch:1.7.1
  env_file:
    - .common.env
