# This common-services.yml definition is for building & unit testing the spira project only. It does not expose any ports
#   so that many builds can run concurrently without causing a port collision.

# This common-services.yml definition holds all the image definitions and environment linking for the images.
# It is intended to use the docker-compose extends functionality to use these definitions to build a docker-compose file

datavolume:
  image: spira/docker-data
  volumes:
    - /data:/data
  privileged: true

spira:
  image: spira/spira
  volumes:
    - /data #note we are not mounting to host. otherwise it would be /qa/data

logviewer:
  image: spira/docker-clarity

database:
  image: postgres:9.4
  env_file:
    - .common.env
    - .local.env

vanilladatabase:
  image: mariadb:10.0
  env_file:
    - .common.env
    - .local.env

cache:
  image: redis

queue:
  image: spira/docker-beanstalkd

queuerunner:
  image: spira/docker-artisan-queue-runner
  env_file:
    - .common.env
    - .local.env

mailcatcher:
  image: schickling/mailcatcher

php:
  image: spira/docker-hhvm
  env_file:
    - .common.env
    - .local.env
    - .secret.env
  privileged: true

web:
  image: spira/docker-nginx
  env_file:
    - .common.env
    - .local.env
  privileged: true

devtools:
  image: spira/docker-dev-tools:latest
#  image: spira/docker-dev-tools:phantomjs-1.9.8
  working_dir: /data
  privileged: true
  env_file:
    - .common.env
    - .local.env
    - .secret.env

apimock:
  image: spira/docker-drakov
  env_file:
    - .common.env
    - .local.env