service_name: travis-ci

# for php-coveralls
src_dir: app
coverage_clover:
  - reports/coverage/api/clover.xml #api
  - reports/coverage/app/clover.xml #app
json_path: reports/coverage/coveralls-upload.json